=== PIPIKAI/balatro-mod-index/schema/meta.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Balatro Mod Metadata",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "requires-steamodded": {
      "type": "boolean"
    },
    "requires-talisman": {
      "type": "boolean"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Content",
          "Joker",
          "Quality of Life",
          "Technical",
          "Miscellaneous",
          "Resource Packs",
          "API",
          "Patch"
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "author": {
      "type": "string"
    },
    "repo": {
      "type": "string",
      "format": "uri"
    },
    "downloadURL": {
      "type": "string",
      "format": "uri"
    },
    "folderName": {
      "type": "string",
      "pattern": "^[^<>:\"/\\|?*]+$"
    },
    "version": {
      "type": "string"
    },
    "automatic-version-check": {
      "type": "boolean"
    }
  },
  "required": [
    "title",
    "requires-steamodded",
    "requires-talisman",
    "categories",
    "author",
    "repo",
    "downloadURL",
    "version"
  ]
}

=== PIPIKAI/balatro-mod-index/mods/RattlingSnow353@SnowsMods/meta.json
{
  "title": "Snows Mods",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content"
  ],
  "author": "RattlingSnow353",
  "repo": "https://github.com/RattlingSnow353/Snow-s-Mods",
  "downloadURL": "https://github.com/RattlingSnow353/Snow-s-Mods/archive/refs/heads/main.zip",
  "automatic-version-check": true,
  "version": "0b38ad9"
}

=== PIPIKAI/balatro-mod-index/mods/Garb@GARBSHIT/meta.json
{
  "title": "GARBSHIT",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content"
  ],
  "author": "Garb",
  "repo": "https://github.com/Gainumki/GARBSHIT.git",
  "downloadURL": "https://github.com/Gainumki/GARBSHIT/archive/refs/heads/main.zip",
  "folderName": "GARBSHIT",
  "automatic-version-check": true,
  "version": "de0c578"
}

=== PIPIKAI/balatro-mod-index/mods/Icecanno@MobileBalatroDargOS/meta.json
{
  "title": "Mobile_Balatro_Drag_Operation_Services",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Patch"
  ],
  "author": "Icecanno",
  "repo": "https://github.com/Icecanno/Mobile_Balatro_Drag_Operation_Services",
  "downloadURL": "https://github.com/Icecanno/Mobile_Balatro_Drag_Operation_Services/archive/refs/heads/main.zip",
  "version": "4cceb2c",
  "automatic-version-check": true
}

=== PIPIKAI/balatro-mod-index/mods/wingedcatgirl@MintysSillyMod/meta.json
{
  "title": "Menthol",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content"
  ],
  "author": "wingedcatgirl",
  "repo": "https://github.com/wingedcatgirl/MintysSillyMod",
  "downloadURL": "https://github.com/wingedcatgirl/MintysSillyMod/releases/download/v1.0.0/Menthol-1.0.0.zip",
  "automatic-version-check": false,
  "version": "v1.0.0"
}

=== PIPIKAI/balatro-mod-index/mods/JosephPB09@CuriLatro/meta.json
{
  "title": "CuriLatro",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Resource Packs"
  ],
  "author": "JosephPB09 and Balatro fans",
  "repo": "https://github.com/JosephPB0909/CuriLatro",
  "downloadURL": "https://github.com/JosephPB0909/CuriLatro/archive/refs/tags/mod.zip",
  "folderName": "CuriLatro",
  "version": "mod",
  "automatic-version-check": true
}

=== PIPIKAI/balatro-mod-index/mods/PIPIKAI@MobileLikeDragging/meta.json
{
  "title": "MobileLikeDragging",
  "requires-steamodded": false,
  "requires-talisman": false,
  "categories": [
    "Patch"
  ],
  "author": "PIPIKAI",
  "repo": "https://github.com/PIPIKAI/MobileLikeDragging",
  "downloadURL": "https://github.com/PIPIKAI/MobileLikeDragging/archive/refs/heads/main.zip",
  "automatic-version-check": true,
  "version": "67421f4"
}

=== PIPIKAI/balatro-mod-index/mods/PIPIKAI@BalatroGoldFinger/meta.json
{
  "title": "BalatroGoldFinger",
  "requires-steamodded": false,
  "requires-talisman": false,
  "categories": [
    "Patch"
  ],
  "author": "PIPIKAI",
  "repo": "https://github.com/PIPIKAI/BalatroGoldFinger",
  "downloadURL": "https://github.com/PIPIKAI/BalatroGoldFinger/archive/refs/heads/main.zip",
  "automatic-version-check": true,
  "version": "2ef68c4"
}

=== PIPIKAI/balatro-mod-index/mods/peakshitposts@peakshitmod/meta.json
{
  "title": "peakshitmod",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content",
    "Joker"
  ],
  "author": "peakshitposts",
  "repo": "https://github.com/peakshitposts/peakshitmod",
  "downloadURL": "https://github.com/peakshitposts/peakshitmod/releases/latest/download/peakshitmod-main.zip",
  "folderName": "peakshitmod",
  "version": "evennewer",
  "automatic-version-check": true
}
