=== PIPIKAI/balatro-mod-index/schema/meta.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Balatro Mod Metadata",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "requires-steamodded": {
      "type": "boolean"
    },
    "requires-talisman": {
      "type": "boolean"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Content",
          "Joker",
          "Quality of Life",
          "Technical",
          "Miscellaneous",
          "Resource Packs",
          "API",
          "Patch"
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "author": {
      "type": "string"
    },
    "repo": {
      "type": "string",
      "format": "uri"
    },
    "downloadURL": {
      "type": "string",
      "format": "uri"
    },
    "folderName": {
      "type": "string",
      "pattern": "^[^<>:\"/\\|?*]+$"
    },
    "version": {
      "type": "string"
    },
    "automatic-version-check": {
      "type": "boolean"
    }
  },
  "required": [
    "title",
    "requires-steamodded",
    "requires-talisman",
    "categories",
    "author",
    "repo",
    "downloadURL",
    "version"
  ]
}

=== PIPIKAI/balatro-mod-index/mods/MothBall@ModOfTheseus/meta.json
{
  "title": "Mod of Theseus",
  "requires-steamodded": true,
  "requires-talisman": true,
  "categories": [
    "Content",
    "Joker"
  ],
  "author": "MothBall",
  "repo": "https://github.com/Mod-Of-Theseus/Mod-Of-Theseus",
  "downloadURL": "https://github.com/Mod-Of-Theseus/Mod-Of-Theseus/archive/refs/heads/main.zip",
  "folderName": "ModOfTheseus",
  "version": "a6b5366",
  "automatic-version-check": true
}

=== PIPIKAI/balatro-mod-index/mods/PIPIKAI@BalatroMobilePatch/meta.json
{
  "title": "Balatro-Mobile-Patch",
  "requires-steamodded": false,
  "requires-talisman": false,
  "categories": [
    "Patch"
  ],
  "author": "PIPIKAI",
  "repo": "https://github.com/PIPIKAI/Balatro-Mobile-Patch",
  "downloadURL": "https://github.com/PIPIKAI/Balatro-Mobile-Patch/archive/refs/heads/main.zip",
  "automatic-version-check": true,
  "version": "d767c5b"
}

=== PIPIKAI/balatro-mod-index/mods/AMY@AMY'sWaifus/meta.json
{
  "title": "AMY's Waifu",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Resource Packs"
  ],
  "author": "AMY",
  "repo": "https://github.com/mikamiamy/AMY-s-Balatro-texturepack",
  "downloadURL": "https://github.com/mikamiamy/AMY-s-Balatro-texturepack/archive/refs/heads/main.zip",
  "folderName": "AMY's Waifu",
  "automatic-version-check": true,
  "version": "75fdcbd"
}

=== PIPIKAI/balatro-mod-index/mods/AbsentAbigail@AbsentDealer/meta.json
{
  "title": "Absent Dealer",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content",
    "Joker"
  ],
  "author": "Absent Abigail",
  "repo": "https://github.com/AbsentAbigail/AbsentDealer",
  "downloadURL": "https://github.com/AbsentAbigail/AbsentDealer/releases/latest/download/absentdealer.zip",
  "folderName": "AbsentDealer",
  "version": "v1.3.3",
  "automatic-version-check": true
}

=== PIPIKAI/balatro-mod-index/mods/stupxd@Blueprint/meta.json
{
  "title": "Blueprint",
  "requires-steamodded": false,
  "requires-talisman": false,
  "categories": [
    "Quality of Life"
  ],
  "author": "Stupxd",
  "folderName": "Blueprint",
  "repo": "https://github.com/stupxd/Blueprint",
  "downloadURL": "https://github.com/stupxd/Blueprint/archive/refs/heads/master.zip",
  "automatic-version-check": true,
  "version": "4e18c48"
}

=== PIPIKAI/balatro-mod-index/mods/kcgidw@kcvanilla/meta.json
{
  "title": "KCVanilla",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Joker"
  ],
  "author": "kcgidw",
  "repo": "https://github.com/kcgidw/kcvanilla",
  "downloadURL": "https://github.com/kcgidw/kcvanilla/archive/refs/heads/master.zip",
  "automatic-version-check": true,
  "version": "57a9add"
}

=== PIPIKAI/balatro-mod-index/mods/LazyTurtle33@FireBotModList/meta.json
{
  "title": "FireBotModList",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": ["Technical"],
  "author": "LazyTurtle33",
  "repo": "https://github.com/TheLazyTurtle33/BalatroFireBotModList",
  "downloadURL": "https://github.com/TheLazyTurtle33/BalatroFireBotModList/releases/latest/download/FireBotModList.zip",
  "folderName": "FireBotModList",
  "version": "release",
  "automatic-version-check": true
}

=== PIPIKAI/balatro-mod-index/mods/SirMaiquis@TagManager/meta.json
{
  "title": "TagManager",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Quality of Life",
    "Miscellaneous"
  ],
  "author": "SirMaiquis",
  "repo": "https://github.com/SirMaiquis/Balatro-TagManager",
  "downloadURL": "https://github.com/SirMaiquis/Balatro-TagManager/releases/latest/download/TagManager.zip",
  "folderName": "TagManager",
  "automatic-version-check": true,
  "version": "v1.2.0"
}
