=== PIPIKAI/balatro-mod-index/schema/meta.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Balatro Mod Metadata",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "requires-steamodded": {
      "type": "boolean"
    },
    "requires-talisman": {
      "type": "boolean"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Content",
          "Joker",
          "Quality of Life",
          "Technical",
          "Miscellaneous",
          "Resource Packs",
          "API",
          "Patch"
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "author": {
      "type": "string"
    },
    "repo": {
      "type": "string",
      "format": "uri"
    },
    "downloadURL": {
      "type": "string",
      "format": "uri"
    },
    "folderName": {
      "type": "string",
      "pattern": "^[^<>:\"/\\|?*]+$"
    },
    "version": {
      "type": "string"
    },
    "automatic-version-check": {
      "type": "boolean"
    }
  },
  "required": [
    "title",
    "requires-steamodded",
    "requires-talisman",
    "categories",
    "author",
    "repo",
    "downloadURL",
    "version"
  ]
}

=== PIPIKAI/balatro-mod-index/mods/RoffleChat@Rofflatro/meta.json
{
  "title": "Rofflatro",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content",
    "Joker"
  ],
  "author": "Roffle's Chat",
  "repo": "https://github.com/MamiKeRiko/Rofflatro",
  "downloadURL": "https://github.com/MamiKeRiko/Rofflatro/archive/refs/tags/v1.2.0a.zip",
  "folderName": "Rofflatro",
  "version": "v1.2.0a",
  "automatic-version-check": true
}

=== PIPIKAI/balatro-mod-index/mods/Agoraaa@FlushHotkeys/meta.json
{
  "title": "Flush Hotkeys",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Quality of Life"
  ],
  "author": "Agoraaa",
  "folderName": "FlushHotkeys",
  "repo": "https://github.com/Agoraaa/FlushHotkeys",
  "downloadURL": "https://github.com/Agoraaa/FlushHotkeys/archive/refs/heads/main.zip",
  "automatic-version-check": true,
  "version": "2f0a91f"
}

=== PIPIKAI/balatro-mod-index/mods/SebasContre@Sebalatro/meta.json
{
  "title": "Sebalatro",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Resource Packs"
  ],
  "author": "SebasContre",
  "repo": "https://github.com/sebascontre/sebalatro",
  "downloadURL": "https://github.com/sebascontre/sebalatro/archive/refs/heads/main.zip",
  "folderName": "Sebalatro",
  "automatic-version-check": true,
  "version": "b05df96"
}

=== PIPIKAI/balatro-mod-index/mods/snowylight@Multipack/meta.json
{
  "title": "Starrailevents",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content"
  ],
  "author": "snowylight",
  "repo": "https://github.com/snowylight/Multipack",
  "downloadURL": "https://github.com/snowylight/Multipack/archive/refs/tags/V2.2.0.zip",
  "automatic-version-check": true,
  "version": "V2.2.0"
}

=== PIPIKAI/balatro-mod-index/mods/LazyTurtle33@TurtlesChallenges/meta.json
{
  "title": "TurtlesChallenges",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content"
  ],
  "author": "LazyTurtle33",
  "repo": "https://github.com/TheLazyTurtle33/TurtlesChallenges",
  "downloadURL": "https://github.com/TheLazyTurtle33/TurtlesChallenges/releases/latest/download/TurtlesChallenges.zip",
  "folderName": "TurtlesChallenges",
  "version": "1.5.3",
  "automatic-version-check": true
}

=== PIPIKAI/balatro-mod-index/mods/PIPIKAI@BalatroSettingEnhance/meta.json
{
  "title": "SettingEnhance",
  "requires-steamodded": false,
  "requires-talisman": false,
  "categories": [
    "Patch"
  ],
  "author": "PIPIKAI",
  "repo": "https://github.com/PIPIKAI/Balatro-Setting-Enhance",
  "downloadURL": "https://github.com/PIPIKAI/Balatro-Setting-Enhance/archive/refs/heads/main.zip",
  "automatic-version-check": true,
  "version": "3b5eb2e"
}

=== PIPIKAI/balatro-mod-index/mods/snowylight@Starrailevents/meta.json
{
  "title": "Starrailevents",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Content",
    "Joker"
  ],
  "author": "snowylight",
  "repo": "https://github.com/snowylight/Starrailevents",
  "downloadURL": "https://github.com/snowylight/Starrailevents/archive/refs/heads/main.zip",
  "automatic-version-check": true,
  "version": "v1.1.0"
}

=== PIPIKAI/balatro-mod-index/mods/Eramdam@StickyFingers/meta.json
{
  "title": "Sticky Fingers",
  "requires-steamodded": true,
  "requires-talisman": false,
  "categories": [
    "Quality of Life"
  ],
  "author": "Eramdam",
  "repo": "https://github.com/eramdam/sticky-fingers/",
  "downloadURL": "https://github.com/eramdam/sticky-fingers/archive/refs/heads/main.zip",
  "automatic-version-check": true,
  "version": "4a73d33"
}
